format_version: 2
pipelines:
  Mobile_CommitPhase:
    group: SamplePipeline
    materials:
      backend:
        git: http://git-repo:3000/gogs/sample-pipeline-mobile.git
        branch: master
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Build:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - ./scripts/commit/build.sh
      - Unit_Tests:
          jobs:
            Run_Unit_Tests:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - ./scripts/commit/unit-test.sh
